export const LABELS: any = {
    pt: {
        release: "Lançamento:",
        genre: "Gênero:",
        director: "Diretor:",
        actor: "Ator:",
        actress: "Atriz:",
        directorTitle: "Diretor(a)",
        actorTitle: "Ator",
        actressTitle: "Atriz",
        personId: "ID:",
        personGender: "Gênero:",
        personJob: "Profissão:",
        personBirth: "Nascimento:",
        titleForm: "Título",
        genreForm: "Gênero",
        directorIdForm: "ID do diretor",
        actorIdForm: "ID do ator",
        actressIdForm: "ID da atriz",
        releaseForm: "Lançamento",
        closeModal: "Fechar",
        updateModal: "Atualizar",
        deleteInfo: "Confirma a exclusão de",
        deleteModal: "Excluir",
        done: "Deu certo",
        error: "Algo deu errado",
        newModal: "Cadastrar",
        idForm: "ID"
    },

    en: {
        release: "Release:",
        genre: "Genre:",
        director: "Director:",
        actor: "Actor:",
        actress: "Actress:"
        directorTitle: "Director",
        actorTitle: "Actor",
        actressTitle: "Actress",
        personId: "ID:",
        personGender: "Gender:",
        personJob: "Profession:",
        personBirth: "Date of Birth:",
    }
};
